# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from typing import Any

from networking.graphql_client.base_client import BaseClient
from networking.graphql_client.delete_import import DeleteImport
from networking.graphql_client.get_action_map import GetActionMap
from networking.graphql_client.get_colors import GetColors
from networking.graphql_client.get_gateway_map import GetGatewayMap
from networking.graphql_client.get_ip_protocols import GetIpProtocols
from networking.graphql_client.get_link_type import GetLinkType
from networking.graphql_client.get_management_map import GetManagementMap
from networking.graphql_client.get_network_obj_type_map import GetNetworkObjTypeMap
from networking.graphql_client.get_service_obj_type_map import GetServiceObjTypeMap
from networking.graphql_client.get_track_map import GetTrackMap
from networking.graphql_client.get_user_obj_type_map import GetUserObjTypeMap


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def delete_import(self, import_id: Any, **kwargs: Any) -> DeleteImport:
        query = gql("""
            mutation deleteImport($importId: bigint!) {
              delete_import_control(where: {control_id: {_eq: $importId}}) {
                affected_rows
              }
            }
            """)
        variables: dict[str, object] = {"importId": import_id}
        response = self.execute(
            query=query, operation_name="deleteImport", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteImport.model_validate(data)

    def get_action_map(self, **kwargs: Any) -> GetActionMap:
        query = gql("""
            query getActionMap {
              stm_action {
                action_name
                action_id
                allowed
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="getActionMap", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetActionMap.model_validate(data)

    def get_track_map(self, **kwargs: Any) -> GetTrackMap:
        query = gql("""
            query getTrackMap {
              stm_track {
                track_name
                track_id
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="getTrackMap", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetTrackMap.model_validate(data)

    def get_link_type(self, **kwargs: Any) -> GetLinkType:
        query = gql("""
            query getLinkType {
              stm_link_type {
                id
                name
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="getLinkType", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetLinkType.model_validate(data)

    def get_colors(self, **kwargs: Any) -> GetColors:
        query = gql("""
            query getColors {
              stm_color {
                color_id
                color_name
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="getColors", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetColors.model_validate(data)

    def get_network_obj_type_map(self, **kwargs: Any) -> GetNetworkObjTypeMap:
        query = gql("""
            query getNetworkObjTypeMap {
              stm_obj_typ {
                obj_typ_name
                obj_typ_id
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="getNetworkObjTypeMap",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetNetworkObjTypeMap.model_validate(data)

    def get_service_obj_type_map(self, **kwargs: Any) -> GetServiceObjTypeMap:
        query = gql("""
            query getServiceObjTypeMap {
              stm_svc_typ {
                svc_typ_name
                svc_typ_id
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="getServiceObjTypeMap",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetServiceObjTypeMap.model_validate(data)

    def get_user_obj_type_map(self, **kwargs: Any) -> GetUserObjTypeMap:
        query = gql("""
            query getUserObjTypeMap {
              stm_usr_typ {
                usr_typ_name
                usr_typ_id
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="getUserObjTypeMap",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetUserObjTypeMap.model_validate(data)

    def get_ip_protocols(self, **kwargs: Any) -> GetIpProtocols:
        query = gql("""
            query getIpProtocols {
              stm_ip_proto {
                ip_proto_id
                ip_proto_name
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="getIpProtocols", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetIpProtocols.model_validate(data)

    def get_gateway_map(self, **kwargs: Any) -> GetGatewayMap:
        query = gql("""
            query getGatewayMap {
              device {
                mgm_id
                dev_id
                dev_uid
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="getGatewayMap", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetGatewayMap.model_validate(data)

    def get_management_map(self, mgm_id: int, **kwargs: Any) -> GetManagementMap:
        query = gql("""
            query getManagementMap($mgmId: Int!) {
              management(where: {mgm_id: {_eq: $mgmId}}) {
                mgm_id
                mgm_uid
                sub_managers: managementByMultiDeviceManagerId {
                  mgm_id
                  mgm_uid
                }
              }
            }
            """)
        variables: dict[str, object] = {"mgmId": mgm_id}
        response = self.execute(
            query=query,
            operation_name="getManagementMap",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetManagementMap.model_validate(data)
