# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from typing import Optional

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class DeleteImport(BaseModel):
    delete_import_control: Optional["DeleteImportDeleteImportControl"]


class DeleteImportDeleteImportControl(BaseModel):
    affected_rows: int


DeleteImport.model_rebuild()
