# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetManagementMap(BaseModel):
    management: list["GetManagementMapManagement"]


class GetManagementMapManagement(BaseModel):
    mgm_id: int
    mgm_uid: str
    sub_managers: list["GetManagementMapManagementSubManagers"]


class GetManagementMapManagementSubManagers(BaseModel):
    mgm_id: int
    mgm_uid: str


GetManagementMap.model_rebuild()
GetManagementMapManagement.model_rebuild()
