# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from typing import Optional

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetServiceObjTypeMap(BaseModel):
    stm_svc_typ: list["GetServiceObjTypeMapStmSvcTyp"]


class GetServiceObjTypeMapStmSvcTyp(BaseModel):
    svc_typ_name: Optional[str]
    svc_typ_id: int


GetServiceObjTypeMap.model_rebuild()
