# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetLinkType(BaseModel):
    stm_link_type: list["GetLinkTypeStmLinkType"]


class GetLinkTypeStmLinkType(BaseModel):
    id: int
    name: str


GetLinkType.model_rebuild()
