# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetNetworkObjTypeMap(BaseModel):
    stm_obj_typ: list["GetNetworkObjTypeMapStmObjTyp"]


class GetNetworkObjTypeMapStmObjTyp(BaseModel):
    obj_typ_name: str
    obj_typ_id: int


GetNetworkObjTypeMap.model_rebuild()
