# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetTrackMap(BaseModel):
    stm_track: list["GetTrackMapStmTrack"]


class GetTrackMapStmTrack(BaseModel):
    track_name: str
    track_id: int


GetTrackMap.model_rebuild()
