# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from typing import Optional

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetGatewayMap(BaseModel):
    device: list["GetGatewayMapDevice"]


class GetGatewayMapDevice(BaseModel):
    mgm_id: int
    dev_id: int
    dev_uid: Optional[str]


GetGatewayMap.model_rebuild()
