# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from typing import Optional

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetUserObjTypeMap(BaseModel):
    stm_usr_typ: list["GetUserObjTypeMapStmUsrTyp"]


class GetUserObjTypeMapStmUsrTyp(BaseModel):
    usr_typ_name: Optional[str]
    usr_typ_id: int


GetUserObjTypeMap.model_rebuild()
