# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetActionMap(BaseModel):
    stm_action: list["GetActionMapStmAction"]


class GetActionMapStmAction(BaseModel):
    action_name: str
    action_id: int
    allowed: bool


GetActionMap.model_rebuild()
