# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from typing import Optional

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetIpProtocols(BaseModel):
    stm_ip_proto: list["GetIpProtocolsStmIpProto"]


class GetIpProtocolsStmIpProto(BaseModel):
    ip_proto_id: int
    ip_proto_name: Optional[str]


GetIpProtocols.model_rebuild()
