# Generated by ariadne-codegen
# Source: roles/importer/files/importer/networking/graphql/

from roles.importer.files.importer.networking.graphql_client.base_model import BaseModel


class GetColors(BaseModel):
    stm_color: list["GetColorsStmColor"]


class GetColorsStmColor(BaseModel):
    color_id: int
    color_name: str


GetColors.model_rebuild()
